### ISSUE TITLE
Thanks! ✨

### ISSUE THREAD

**Issue by dubstrike** [tvkhoa/react-tippy#1]
Couldn't find you on Twitter, so just dropping by over here to say thanks for making this package! I was looking for something like this just a few days ago.

![you're awesome](https://media1.giphy.com/media/mbhseRYedlG5W/giphy.gif)

**Comment by tvkhoa** [comment]
👍  Thanks for your appreciation. 
Please feel free to let me know if you have any issue when using react-tippy
btw, just follow you on twitter
