### ISSUE TITLE
tooltip moves with mouse and creates scroll . how do i close tooltip on scroll and keep it inside the scrollabel container without overflowing

### ISSUE THREAD

**Issue by paigeflourin** [tvkhoa/react-tippy#100]
Hi implemented this tooltip to my project but it doesn't behave the way i want it to. when i click the button to open the tooltip and scroll to the top of my page. it causes an extra toolbar to appear.

![final 1](https://user-images.githubusercontent.com/6951524/49558496-3e1e4c00-f946-11e8-96fa-a1e50bb35e8b.gif)

the content of the tooltip is a component but i don't that that matters. this is how i use the tooltip from my parent component.

```
                              <Tooltip 
                                position="left-end"                              
                                trigger="click" 
                                arrow      
                                offset={0}                  
                                html= {<div><QnAPreviewPanel qnaItem={row} /></div>}
                            >
                              <button>Preview</button>
                            </Tooltip>
``` 
based from the docs and examples the toolstips stay in place, why does mine follow my screen scrolling? kindly advise me if this issue is not related to the tooltip component.

**Comment by ruaanvds** [comment]
I was experiencing the same issue and after a bit of experimentation, the following works for me: 

```
sticky={true}
stickyDuration={0}
```

**Comment by paigeflourin** [comment]
@ruaanvds , thank you! but i still have that extra scrollbar but i don't think its related to this component.

**Comment by paigeflourin** [comment]
okay nevermind its just a problem with scrolling.
