### ISSUE TITLE
Unhandled rejection referenceError: Element is not defined

### ISSUE THREAD

**Issue by brianlovin** [tvkhoa/react-tippy#108]
From `src/Tooltip/js/utils/matches.js`, `Unhandled rejection referenceError: Element is not defined` gets thrown and crashes deployments where this gets built on the server. I'm currently trying to use this on withspectrum/spectrum, deployed with Now:

<img width="1392" alt="screenshot 2019-03-06 08 34 55" src="https://user-images.githubusercontent.com/1923260/53885003-c31f0d00-3fea-11e9-9e92-1d78a63dd5af.png">

This error *seems* to make sense, although the original SSR check should have caught it beforehand. I'm wondering if the error gets thrown when compiled with babel or something?

**Comment by brianlovin** [comment]
I forked the repo, and in that file I just changed the following line:

```
export const matches = defaultMatchSelector
```

This fixed the problem. So it seems that there's a problem in the SSR detection flag that causes the server to try and evaluate `Element`

**Comment by atomiks** [comment]
@brianlovin  this package is unmaintained, I recommend you use [@tippy.js/react](https://github.com/atomiks/tippy.js-react) instead.  Spectrum is pretty awesome/important so I don't want to see you use an unmaintained package (and very old version of tippy.js from 2017). Many bugs have been fixed and features released and the newest version has matured a lot compared to the wild west development it was undergoing in 2017/2018

**Comment by brianlovin** [comment]
Thanks a bunch for the note @atomiks - funny enough, I tried using @tippy.js/react at first and couldn't manage to get it up and running, while this package had no problems at all (except for the deployment issue above, which was a quick fix).

I'll add a to-do to migrate to the latest package at some point then :)

**Comment by atomiks** [comment]
Feel free to make an issue on the repo, it would probably help others. Someone else experienced a strange error too, but it works fine when importing on CRA, CodeSandbox, and Parcel 🙁

**Comment by brianlovin** [comment]
Gotcha. We use a modified CRA, but also do some SSR stuff that might make for an interesting implementation. Will follow up with issues if anything comes up though.
