### ISSUE TITLE
No context provided to HTML prop

### ISSUE THREAD

**Issue by maxsalven** [tvkhoa/react-tippy#11]
If I have a tooltip with an html prop that is a React component, and that component in turn uses `connect()` from `redux`, then you'll get an error:
`Uncaught Error: Could not find "store" in either the context or props of "Connect(...)".`

You can see how `react-portal` does it here:
https://github.com/tajo/react-portal/pull/23

**Comment by tvkhoa** [comment]
hi @maxsalven . Fixed in 1.0.1

Feel free to fire an issue if you have any problem.

**Comment by arjunskumar47** [comment]
I'm still having the same issue on `v1.2.2`

**Comment by felixschul** [comment]
@arjunskumar47 You have to enable "useContext".

**Comment by JonathanKolnik** [comment]
I had to explicitly set useContext={true} I thought I could use the short hand but that doesn't work.

**Comment by feimosi** [comment]
I have the same issue:
`
Uncaught Invariant Violation: Could not find "store" in the context of "Connect(SignInButton)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(SignInButton) in connect options.
`

`useContext={true}` doesn't help. I'm using react@16.7.0 and react-tippy@1.2.3

**Comment by nicubarbaros** [comment]
have the same problem. FK!
