### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by StevenLangbroek** [tvkhoa/react-tippy#117]
Hey!

I noticed this repo is unmaintained:

- 25 PRs open
- 54 Issues open
- Last commit to master in October 2018
- Unnecessary dependency on CSS
- Major version of core package released, no update available

There are official [React bindings to Tippy](https://github.com/atomiks/tippy.js-react) now. Maybe put up a deprecation notice, or look for a new maintainer? It'll also mean you don't have to monitor this repo anymore, maybe freeing up time / attention / energy for something you're more interested in maintaining <3

Thanks.

**Comment by tvkhoa** [comment]
Hi, 

I'm sorry I didn't have enough focus to maintain it. However, now is actually a good time for me to restart the maintenance.

Regarding to your concern, I already explained here https://github.com/tvkhoa/react-tippy/issues/105#issuecomment-544486673
