### ISSUE TITLE
Tooltip doesn't always dismiss

### ISSUE THREAD

**Issue by maxsalven** [tvkhoa/react-tippy#12]
Use the exact same code as https://github.com/tvkhoa/react-tippy/issues/10#issuecomment-312562581 but wrap the drop down menu items in tooltips themselves (in the `Example` component):

```javascript
            <Tooltip title="This is a tip" position="right">
              <div
                key={option}
                onClick={() => this.setState({ value: option })}
              >
                {option} – {isActive ? "Active" : "Not Active"}
              </div>
            </Tooltip>
```

Now when you click an item, the "This is a tip" tooltip still stays on screen, even though the child component no longer exists:

![rt0pg3kumj](https://user-images.githubusercontent.com/4144910/28007184-fd7eb226-6584-11e7-9fdc-b3dfb9b17bcf.gif)

**Comment by tvkhoa** [comment]
This lib support some callback function.

For your issue, I think you can fix it with `onHidden` callback

And please update it to `1.2.2` to use this callback.

Thank you 🍡
