### ISSUE TITLE
Fixed Position

### ISSUE THREAD

**Issue by maxsalven** [tvkhoa/react-tippy#13]
Is there a way to fix the position, so if you specify `position="bottom"` and e.g. `fixedPosition={true}` , then the tooltip will always be on the bottom of the element, even if it would be off the screen?

**Comment by maxsalven** [comment]
Solved using 'popperOptions'. Maybe would be nice to make this a first class prop.

```javascript
popperOptions={{
  modifiers: {
    preventOverflow: {
      enabled: false,
    },
    flip: {
      enabled: false,
    },
  },
}}
```

**Comment by norama** [comment]
I had to add `hide: { enabled: false }` as well, otherwise there is popperjs warning:
https://github.com/atomiks/tippyjs/issues/105

So I am using:

```
popperOptions={{
    modifiers: {
        preventOverflow: { enabled: false },
        flip: { enabled: false },
        hide: { enabled: false }
     }
}}
```

**Comment by 6zun9** [comment]
can you guys add what  kind of issue that you have solved like link for jsfiddle or something like that ?. I tried to implement chat like behavior on a app where you show an options to chat at bottom right and when you click on it it opens an options for more just at the top of button but the pop over is appearing on the page top area.
