### ISSUE TITLE
How to target the .tippy-popper instance

### ISSUE THREAD

**Issue by serabakpak** [tvkhoa/react-tippy#18]
Hi there, is there a way to target the top-most `.tippy-popper` instance? I'm trying to give it a `className` of my own.

**Comment by omRm** [comment]
Have a look at themes: https://atomiks.github.io/tippyjs/#creating-themes
maybe its what your looking for

**Comment by serabakpak** [comment]
Thanks for your quick response! Worked like a charm.

**Comment by tvkhoa** [comment]
Seem like you got your answer.

Thank you @omRm 🍡

**Comment by CookPete** [comment]
See also: https://github.com/tvkhoa/react-tippy/issues/83#issuecomment-666289769
