### ISSUE TITLE
How to manually close a toolTip

### ISSUE THREAD

**Issue by LentnerStefan** [tvkhoa/react-tippy#2]
Hi!

I'm having trouble figuring out how to manually close an interactive tooltip. 
At first i thought there would be a method in the Tooltip component allowing me to show/hide it. ( by refs) but there is none. 
I also tried working with the "disabled" props, but it's not the behaviour i'm looking for.
Am i missing something?

Thank you for the great work!

**Comment by tvkhoa** [comment]
At first, I think tooltip just can only open when user hover or click on it. Therefore, I haven't implemented the 'open manually' feature.
But, it makes sense if we can have the `open` and `onRequestClose` prop to show/hide it.
Let me implement it in the next release.

**Comment by tvkhoa** [comment]
@LentnerStefan Just enhance it in release v0.10.0.
Please feel free to fire an issue if you have any problem.

**Comment by LentnerStefan** [comment]
Appreciated, thanks!
