### ISSUE TITLE
How to use a reference element to attach the Tooltip to

### ISSUE THREAD

**Issue by jordanwink201** [tvkhoa/react-tippy#21]
**_This is not an issue but a question_**

@tvkhoa How can I achieve this in `react-tippy`?
```
const el = document.querySelector('#myElement')
tippy(el)
```
I don't see in the documentation where to attach the tooltip to a reference element.
Maybe something like this ?
```
return (
      <Tooltip
        title="Welcome to React"
        position="bottom"
        trigger="click"
      >
        {document.querySelector('#myElement')}
      </Tooltip>
)
``` 

Thanks!

**Comment by tvkhoa** [comment]
@jordanwink201
Pls check new version `1.2.2`. We support `rawTemplate` props to help you render DOM element in tooltip content.

```
<Tooltip
          trigger="click"
          rawTemplate={document.querySelector('#rawHTML')}
>
          Raw html
        </Tooltip>
```

Thanks

**Comment by tvkhoa** [comment]
@jordanwink201 
It seem like your problem is render DOM element inside React element.

Therefore, I don't think we can achieve it in this lib, it's out of its scope.

Sorry and thank you 🍡
