### ISSUE TITLE
Error thrown while mounting/unMounting if using html prop.

### ISSUE THREAD

**Issue by renatodeleao** [tvkhoa/react-tippy#28]
Howdy! First of all thanks for the work on this wrapper, mega helpful ✋ 

# Context
So i'm using `react-tippy` as an easy way to have dynamically positioned [context-menus/dropdowns](https://material.io/guidelines/components/menus.html#menus-usage) on my app, similar to material design ones and it does a pretty damn good job at it.

# Scenario/Demo
I have a searchable cards list. Cards are removed/unmounted based on the search query.
A simple demo can be found here: 
https://codesandbox.io/s/j39z5pj32y 

# Steps to Reproduce
1. Have a `<Tooltip>` that includes some HTML at `html` prop.
1. Add/remove it from the DOM dynamically (search is a simple example)

# Expected Behavior
No errors should be thrown on mount/unmount components containing an instance of `react-tippy`.

# Current Behavior
An error is thrown by `react-tippy`, on dynamically mount/unmount components to the DOM.

```bash
Uncaught TypeError: html.replace is not a function
    at Tippy.update (dll.js:29286)
    at Tooltip._updateTippy (dll.js:27466)
    at Tooltip.componentDidUpdate (dll.js:27401)
    at measureLifeCyclePerf (dll.js:8745)
    at dll.js:9399
    at CallbackQueue.notifyAll (dll.js:6003)
    at ReactReconcileTransaction.close (dll.js:11907)
    at ReactReconcileTransaction.closeAll (dll.js:4285)
    at ReactReconcileTransaction.perform (dll.js:4232)
    at ReactUpdatesFlushTransaction.perform (dll.js:4219)
    at ReactUpdatesFlushTransaction.perform (dll.js:1233)
    at Object.flushBatchedUpdates (dll.js:1316)
    at ReactDefaultBatchingStrategyTransaction.closeAll (dll.js:4285)
    at ReactDefaultBatchingStrategyTransaction.perform (dll.js:4232)
    at Object.batchedUpdates (dll.js:6601)
    at Object.batchedUpdates (dll.js:1241)
    at dispatchEvent (dll.js:18343)
update @ dll.js:29286
_updateTippy @ dll.js:27466
componentDidUpdate @ dll.js:27401
measureLifeCyclePerf @ dll.js:8745
(anonymous) @ dll.js:9399
notifyAll @ dll.js:6003
close @ dll.js:11907
closeAll @ dll.js:4285
perform @ dll.js:4232
perform @ dll.js:4219
perform @ dll.js:1233
flushBatchedUpdates @ dll.js:1316
closeAll @ dll.js:4285
perform @ dll.js:4232
batchedUpdates @ dll.js:6601
batchedUpdates @ dll.js:1241
dispatchEvent @ dll.js:18343
```

# Context (Environment)
- `react-tippy@1.2.2` (also found in previous 1.0.2 version, i've upgraded to test it)
- `react@15.5.3`

# Notes
1. The error doesn't occur if `HTML` prop is not used.
1. using `unmountHTMLWhenHide`does not affect the results
1. On my app, which is kind of big and using redux, this error completely freezes/crashed the app having to reload the browser to get back to it (by removing the `react-tippy` the error disappears). This error is also thown in my "real-life" environment, i've deleted some dozen lines 
```
[getPopperElement]: Element passed as the argument does not exist in the instance
__stack_frame_overlay_proxy_console__ @ bundle.js:97339
getPopperElement @ bundle.js:113364
_destroyTippy @ bundle.js:111916
componentWillUnmount @ bundle.js:111745
(anonymous) @ bundle.js:82432
measureLifeCyclePerf @ bundle.js:82099
unmountComponent @ bundle.js:82441
....
dispatchEvent @ bundle.js:87036
bundle.js:113413 Uncaught TypeError: Cannot read property 'settings' of undefined
    at Tippy.updateSettings (bundle.js:113413)
    at Tooltip._updateSettings (bundle.js:111826)
    at Tooltip._destroyTippy (bundle.js:111917)
    at Tooltip.componentWillUnmount (bundle.js:111745)
    at bundle.js:82432
    at measureLifeCyclePerf (bundle.js:82099)
    at ReactCompositeComponentWrapper.unmountComponent (bundle.js:82431)
    at Object.unmountComponent (bundle.js:89084)
    at Object.updateChildren (bundle.js:81895)
...
 
    at ReactCompositeComponentWrapper.receiveComponent (bundle.js:82570)
updateSettings @ bundle.js:113413
_updateSettings @ bundle.js:111826
_destroyTippy @ bundle.js:111917
componentWillUnmount @ bundle.js:111745
(anonymous) @ bundle.js:82432
measureLifeCyclePerf @ bundle.js:82099
unmountComponent @ bundle.js:82431
unmountChildren @ bundle.js:88512
...
runBatchedUpdates @ bundle.js:89929
perform @ bundle.js:89868
flushBatchedUpdates @ bundle.js:89951
closeAll @ bundle.js:92005
perform @ bundle.js:91952
batchedUpdates @ bundle.js:89876
dispatchEvent @ bundle.js:87036
Uncaught TypeError: Cannot read property 'getHostNode' of null
```
Which my have something to do with #17  

----
Hope you can help me, keep up the good work! 🍀

**Comment by Tsury** [comment]
Suffering from *exactly* the same thing. Have a redux app with cards which use HTML tips. The cards get removed/added from/to DOM. Getting the `Cannot read property 'settings' of undefined` error, users reporting a complete freeze of the app which requires a refresh. Waiting for a fix, thanks!

**Comment by KatSick** [comment]
same here

**Comment by abdulpapalek** [comment]
unmountHTMLWhenHide does now work, can anyone beside me confirm this? , please i need this working

**Comment by abdulpapalek** [comment]
heeeeeeeeeeeeeeeeeeeeeeeeelp!!!!!! why is not unmounting

**Comment by oldo** [comment]
Also experiencing this issue. Very nicely explained @renatodeleao

**Comment by oldo** [comment]
It's a shame that no one seems to be maintaining this most excellent component.

**Comment by lmikos-neurosys** [comment]
The same problem.

**Comment by AndrejGajdos** [comment]
+1

**Comment by meesvandongen** [comment]
Removing the title attribute when using html seemed to work for me.

**Comment by renatodeleao** [comment]
@meesvandongen it's been long time since i've reported the issue i don't even remember how i solved it but thanks for your reply!

For everyone in this thread removing the title attribute does indeed stop the `html.replace` error at least in my codesandbox demo. We still get the error on clicking the tooltip (which doesn't break the demo), but that might be related with #17 

```shell
react-tippy.js:577 Uncaught TypeError: Cannot read property 'settings' of undefined
    at HTMLDocument.i (VM426 common-sandbox.68dd25b4.js:2011)
```

If this is expected, docs should reflect it but i don't think this project is maintained anymore.. so Good luck y'all!

**Comment by tvkhoa** [comment]
Hi all,
I merge the PR https://github.com/tvkhoa/react-tippy/pull/36 and publish a new build. Just add 1 more check for settings data.
I will close this issue here. Feel free to reopen if it happens again so that we can investigate more

**Comment by egoreburial** [comment]
i'm still getting this error @ 1.4.0 version. Uncaught TypeError: html.replace is not a function, and seems like unmountHTMLWhenHide really doesn't work. Need some help with this ASAP!

**Comment by amirho1** [comment]
I'm getting an error in console:  Element passed as the argument does not exist in the instance 
div
@egoreburial did you find any solution?

**Comment by meesvandongen** [comment]
> I'm getting an error in console: Element passed as the argument does not exist in the instance div @\egoreburial did you find any solution?

You should probably be using https://www.npmjs.com/package/@tippyjs/react instead of this (same API). Or https://floating-ui.com/docs/getting-started as they are suggesting.
