### ISSUE TITLE
More than one tooltip on a single element

### ISSUE THREAD

**Issue by hjaltisan** [tvkhoa/react-tippy#29]
It would be a really nice feature to be able to have more than one tooltip on the same element.
For example lets say you have a button that is very small and only an icon. I would have a tooltip for the button to describe what it does, and then when you click the button I would like to open an interactive tooltip. Would this be possible?

**Comment by oldo** [comment]
@hjaltisan I achieved this by attaching `onMouseEnter` and `onMouseLeave` event listeners to the div that the tooltip is attached to. I'm also passing a prop `this.props.option.showConfirmTooltip` that overrides the mouse enter or leave action. `showConfirmTooltip` also dictates the content of the `html`.

```
class ButtonGroup extends Component {
  constructor() {
    super();
    this.state = { open: false };
  }

  render() {
    const { option } = this.props;

    return (
      <Tooltip
        title={option.key}
        open={option.showConfirmTooltip || this.state.open}
        theme={option.showConfirmTooltip ? 'light' : 'dark'}
        interactive
        position="bottom"
        animation="fade"
        duration="200"
        distance={option.iOSWiredIcon ? 3 : 18}
        arrow
        unmountHTMLWhenHide
        html={
          option.showConfirmTooltip ? (
            <ConfirmTooltip
              onConfirm={option.onConfirm}
              onCancel={option.onCancel}
            />
          ) : (
            <span>{option.tooltip}</span>
          )
        }
      >
        <div
          onMouseEnter={() => this.setOpen(true)}
          onMouseLeave={() => this.setOpen(false)}
        >
          {label}
        </div>
      </Tooltip>
    );
  };
}
```

**Comment by hjaltisan** [comment]
That's brilliant! Thank you for sharing!

**Comment by oldo** [comment]
Stoked that helped :-)
