### ISSUE TITLE
Custom HTML tag

### ISSUE THREAD

**Issue by jebarjonet** [tvkhoa/react-tippy#30]
I noticed `react-tippy` set the wrapper tag as a `div`, which gives some warning from React if used inside a `p` for example

<img width="306" alt="screen shot 2017-10-16 at 5 44 09 pm" src="https://user-images.githubusercontent.com/4401230/31621330-b78ec348-b299-11e7-830f-02bfd5db1a97.png">

There could be a custom `Tag` feature (see an example here https://github.com/reactstrap/reactstrap/blob/master/src/Button.js#L72) so we could set it to something else (like a `span`) what do you think?

**Comment by bernatfortet** [comment]
Any updates on this one?
