### ISSUE TITLE
Mounting and Unmounting of complex tooltips

### ISSUE THREAD

**Issue by toc777** [tvkhoa/react-tippy#4]
react-tippy immediately mounts the html attribute component on render. This may not always be  desired if the component fetches data or is reasonably complex (in my case, I render a list with many tooltips, each one fetching data on mount etc).

There are ways of avoiding this, for example using the disabled attribute but this isn't very intuitive and requires that you take control of the opening and closing of the tooltip.

Another issue I've noticed is there is no way to tell react-tippy to destroy the html component when the tooltip is hidden. Again, you can work around this using disabled (although I see an error being thrown onHide when disabled is true) but it isn't obvious that you need to set disabled to true to do this.

It would be great to have some kind of attribute like lazyRender that would only mount the html component when the tooltip is visible and unmount it when it is not visible.

Thanks!

**Comment by tvkhoa** [comment]
hi @toc777 , thanks for your feedback and sorry for late response. I was being busy last week.

Could you please update to version 0.12.1?

- html component's life cycle is working now. You can fetch data in the componentWillMount or componentDidMount.

- By default, html component will be mounted at first show and unmount only when your tooltip component is unmounted. When you set unmountHTMLWhenHide is true, it will be unmounted whenever tooltip is hidden.

**Comment by toc777** [comment]
Awesome! Thank you :)
