### ISSUE TITLE
Error during server side rendering

### ISSUE THREAD

**Issue by jdwillemse** [tvkhoa/react-tippy#5]
```ReferenceError: document is not defined```

I'm trying to use react-tippy in my app that renders in node and browser. Would be great if this were possible

**Comment by tvkhoa** [comment]
@jdwillemse, Could you pls update to 0.12.1 ?

I just added some conditions to check if it's render on server side or not. I haven't tested it yet but it should be worked now.

Let me know if it still has problem with SSR
