### ISSUE TITLE
No default styling applied, despite importing css file

### ISSUE THREAD

**Issue by hundsim** [tvkhoa/react-tippy#6]
Hi! Is there any styling applied by default? I've followed the installation steps (including importing the css file) in the README. 

The pop up works but there's no default styling applied. I don't see any rendered classes at all - is that the problem? And if so, is there an option for that?

This is the code I've used (in a component):

	import 'react-tippy/dist/tippy.css'
	import {
	  Tooltip,
	} from 'react-tippy';

	<Tooltip
	  // options
	  title="Welcome to React"
	  position="bottom"
	  trigger="click"
	>
	  <p>
	    Click here to show popup
	  </p>
	</Tooltip>

**Comment by tvkhoa** [comment]
By default, it should work. Maybe the css doesn't load in your project.
You can inspect element and find `tippy-tooltip` class. After that, you can check tippy style is loaded or not.
