### ISSUE TITLE
div cannot appear as a descendant of p

### ISSUE THREAD

**Issue by mehmetnyarar** [tvkhoa/react-tippy#64]
Hi,

I have anchor tags inside paragraphs which are surrounded by Tooltip components. Tooltips work well but I receive the following error in console:

> validateDOMNesting(...): `<div>` cannot appear as a descendant of `<p>`.

I've tried replacing `<div>` tags with other HTML elements in the source file but no use. Either tooltip looks ugly or the document flow breaks. I can replace `<p>`s with `<div>`s to get rid of the error but it's semantically wrong because the content is supposed to be a paragraph.

Is there any known solution for this?

**Comment by christophedebatz** [comment]
Same error on last version, normal ?

**Comment by stk-dmitry** [comment]
if the library uses [inline style](https://github.com/tvkhoa/react-tippy/blob/6b07902b5535d5e2d41c9ca085c17d69f3c34a00/src/Tooltip/component.js#L254), it could be replace `<div>` with `<span>`? because often tooltips are used in a paragraph
