### ISSUE TITLE
Error while trying to render on the server

### ISSUE THREAD

**Issue by kedmyster** [tvkhoa/react-tippy#7]
Hey @tvkhoa,

There's an error when trying to render the tooltip on the server,
It's caused due to tippy.js trying to hook into client events.
I created a fix for it and it's already merged to latest version of tippy.js. can you update to latest version?

Thanks!

**Comment by tvkhoa** [comment]
I will update it this weekend, but which version you're using now? 0.12.1 ?

**Comment by kedmyster** [comment]
Yep, latest version.
Thanks!

Thanks,
Lior

________________________________

**Comment by scf4** [comment]
Any update?

**Comment by scf4** [comment]
@tvkhoa any update?

**Comment by tvkhoa** [comment]
Just updated to version 0.14.0.
Pls close this issue if it solves your problem.

cc @kedmyster
