### ISSUE TITLE
Tooltip width

### ISSUE THREAD

**Issue by Moeface** [tvkhoa/react-tippy#8]
Thanks for the great work, this is a very useful component.

I just had a quick question about setting the width of the tooltip.

The width of the tooltip is set by `.tippy-popper`, but from what I can tell, none of the available props allow me to add a class at that level in the DOM.  Setting the `theme` prop adds a class to the level below `.tippy-popper`, meaning I'm unable to target and change the width of just this tooltip with CSS.

I realise I can overwrite it with the CSS `width` property, but this makes responsive tooltips harder to achieve.

Is this the case or am I missing something obvious?

**Comment by tvkhoa** [comment]
I will take a look at this weekend. Thanks

**Comment by tvkhoa** [comment]
Added in 1.0.1. You can take a look at the doc https://github.com/tvkhoa/react-tippy#could-i-change-tooltip-style-width-height-

Thank you

**Comment by MoQ93** [comment]
For me, this just increased the width of the content container but not of the tooltip. Thanks

**Comment by SeanRoberts** [comment]
I can't see a way to target or add a class to the tippy-popper instance, which has a max-width of 400px when using the default react-tippy styles.  It would be great if either the theme prop would add a classname to the tippy-popper or if there was a way to apply styles directly to the tippy-popper instance through the props.

**Comment by sbitproz** [comment]
> I can't see a way to target or add a class to the tippy-popper instance, which has a max-width of 400px when using the default react-tippy styles. It would be great if either the theme prop would add a classname to the tippy-popper or if there was a way to apply styles directly to the tippy-popper instance through the props.

Is this still an issue?  My Popup is limited to 400px.  Because it's a react portal, it's no so simple to adjust the width of the component.  I hope a solution will be implemented either where the 400px is removed so the popup wraps the size of the contents or we have a prop to adjust the size.  Any feedback would be great!
