### ISSUE TITLE
Aria accesibily problem with Lighthouse

### ISSUE THREAD

**Issue by EmaSuriano** [tvkhoa/react-tippy#89]
Hi!
I'm having some problems to achieve 100 in Lighthouse and the problem is related to the aria attributes. I didn't find an easy way to send it. I looked inside the documentation and the issues but I didn't find anything related.

This is the report of Lighthouse from the official [demo of react-tippy](https://tvkhoa.github.io/testlib).

![image](https://user-images.githubusercontent.com/3399429/46318607-6a7cbb80-c5d7-11e8-834b-408eabf1586f.png)

**Comment by phamtuan2993** [comment]
Sorry for this inconvenient when using react-tippy, I have made a PR (https://github.com/tvkhoa/react-tippy/pull/90) to improve this, I will update once new version is released to address your issue.

Thanks.

**Comment by phamtuan2993** [comment]
Thank you @EmaSuriano for your feedback,

Sorry for this inconvenient when using react-tippy, I have made a PR (https://github.com/tvkhoa/react-tippy/pull/90) to improve this, I will update once new version is released to address your issue.

Thanks.
