### ISSUE TITLE
IE 11 support?

### ISSUE THREAD

**Issue by chasedeanda** [tvkhoa/react-tippy#9]
I'm getting an error on line 936 
`this.settings = Object.assign(JSON.parse(JSON.stringify(DEFAULTS)), settings);` 
and I'm getting `Object doesn't support property or method 'assign'`. Can you add a polyfill for Object.assign or some other way to get it working in IE?

**Comment by tvkhoa** [comment]
I think the polyfill should be added in your project if you want to support IE 11. Thanks

**Comment by chasedeanda** [comment]
That's what I ended up doing. You should add supported browsers somewhere in the README to let people know.

**Comment by tvkhoa** [comment]
@chasedeanda . Added in 1.0.1. Thank you :)
